#-*- coding: utf-8 -*-

UNKNOWN_SCHOOL_LEVEL = 'UNKNOWN'
ELEMENTARY_SCHOOL_LEVEL = 'ELEMENTARY_SCHOOL'
MIDDLE_SCHOOL_LEVEL = 'MIDDLE_SCHOOL'
HIGH_SCHOOL_LEVEL = 'HIGH_SCHOOL'
OTHER_SCHOOL_LEVEL = 'OTHER_SCHOOL'

UNKNOWN_SCHOOL_KIND = 'UNKNOWN'
NORMAL_SCHOOL_KIND = 'NORMAL_SCHOOL'
GIRL_SCHOOL_KIND = 'GIRL_SCHOOL'
OPEN_SCHOOL_KIND = 'OPEN_SCHOOL'
SPECIAL_SCHOOL_KIND = 'SPECIAL_SCHOOL'
ATTACHED_SCHOOL_KIND = 'ATTACHED_SCHOOL'
BRANCH_SCHOOL_KIND = 'BRANCH_SCHOOL'

SPECIAL_SCIENCE_SCHOOL_KIND = 'SPECIAL_SCIENCE'
SPECIAL_FOREIGN_SCHOOL_KIND = 'SPECIAL_FOREIGN'
SPECIAL_ART_SCHOOL_KIND = 'SPECIAL_ART'
SPECIAL_COMMERCIAL_SCHOOL_KIND = 'SPECIAL_COMMERCIAL'
SPECIAL_TECHNICAL_SCHOOL_KIND = 'SPECIAL_TECHNICAL'
